mutation PerformerCreate($input: PerformerCreateInput!) {
  performerCreate(input: $input) {
    ...PerformerData
  }
}

mutation PerformerUpdate($input: PerformerUpdateInput!) {
  performerUpdate(input: $input) {
    ...PerformerData
  }
}

mutation PerformerSetFavorite($id: ID!, $favorite: Boolean!) {
  performerSetFavorite(id: $id, favorite: $favorite) {
    ...PerformerData
  }
}

mutation PerformerSetRating($id: ID!, $rating100: Int) {
  performerSetRating(id: $id, rating100: $rating100) {
    ...PerformerData
  }
}

mutation BulkPerformerUpdate($input: BulkPerformerUpdateInput!) {
  bulkPerformerUpdate(input: $input) {
    ...PerformerData
  }
}

mutation PerformerDestroy($id: ID!) {
  performerDestroy(input: { id: $id })
}

mutation PerformersDestroy($ids: [ID!]!) {
  performersDestroy(ids: $ids)
}

mutation PerformerMerge($input: PerformerMergeInput!) {
  performerMerge(input: $input) {
    id
  }
}
